# Generated by Django 3.2.3 on 2021-05-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishItems',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_recipebook.dishitems_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dishitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecipeBook.dishitems')),
                ('picture', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Veg', 'Veg'), ('NonVeg', 'NonVeg')], max_length=60)),
                ('total_Rating', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('RecipeBook.dishitems',),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('dishitems_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RecipeBook.dishitems')),
                ('picture', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Veg', 'Veg'), ('NonVeg', 'NonVeg')], max_length=60)),
                ('amount_type', models.CharField(choices=[('gms', 'gms'), ('oneserv', 'oneserv'), ('ml', 'ml')], max_length=60)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('RecipeBook.dishitems',),
        ),
        migrations.CreateModel(
            name='DishIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishItems', models.ManyToManyField(related_name='dishIngredients', to='RecipeBook.DishItems')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dName', to='RecipeBook.dish')),
            ],
        ),
    ]
