# Generated by Django 3.2.3 on 2021-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='test',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
