# Generated by Django 3.2.3 on 2021-05-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MealPlans', '0001_initial'),
        ('RecipeBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgroup',
            name='food_items',
            field=models.ManyToManyField(blank=True, related_name='FoodGroup', to='RecipeBook.DishItems'),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preset', to='MealPlans.preset'),
        ),
        migrations.AddField(
            model_name='days',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MealPlans.mealpreset'),
        ),
    ]
