# Generated by Django 3.2.3 on 2021-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBook', '0001_initial'),
        ('MealPlans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgroup',
            name='food_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='FoodGroup', to='RecipeBook.DishItems'),
        ),
    ]
