# Generated by Django 3.2.3 on 2021-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlans', '0004_alter_foodgroup_food_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplans',
            name='default_day',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], default='MONDAY', max_length=10),
            preserve_default=False,
        ),
    ]
